Application\Map2u\CoreBundle\Entity\UserDrawGeometries:
    type: entity
    table: userdrawgeometries
#    inheritanceType: SINGLE_TABLE
#    discriminatorColumn:
#        name: type
#        type: string
#        length: null
#    discriminatorMap:
#        1: Map2u\CoreBundle\Entity\UserDrawGeometries
#        2: Application\Map2u\CoreBundle\Entity\UserDrawGeometries
    fields:
        images:
            type: string
            length: 2500
            fixed: false
            nullable: true
            column: images       
        video:     
            type: string
            length: 2500
            fixed: false
            nullable: true
            column: video
        audio:     
            type: string
            length: 2500
            fixed: false
            nullable: true
            column: audio            
