Yorku\JuturnaBundle\Entity\Bird:
    type: entity
    table: birds
    gedmo:
    translation:
        locale: localeField
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        scientificName:
            type: string
            length: 255
            nullable: false
            column: scientific_name
        commonName:
            type: string
            length: 255
            nullable: true
            column: common_name
            gedmo:
                - translatable
        iucn:
            type: string
            length: 25
            nullable: true
            column: iucn
        season:
            type: string
            length: 255
            nullable: true
            column: season
        distribution:
            type: string
            length: 255
            nullable: true
            column: distribution
        distribution:
            type: string
            length: 255
            nullable: true
            column: distribution
        rareness:
            type: text
            nullable: true
            column: rareness
        code:
            type: text
            nullable: true
            column: code
        websiteUrl:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: website_url
        imageTip:
            type: string
            length: 125
            fixed: false
            nullable: true
            column: image_tip
        images:
            type: text
            nullable: true
            column: images
        videos:
            type: text
            nullable: true
            column: videos
        audios:
            type: text
            nullable: true
            column: audios
        enabled:
            type: boolean
            column: enabled
            nullable: true
        lng:
            type: decimal
            unsigned: false
            nullable: true
        lat:
            type: decimal
            unsigned: false
            nullable: true
        theGeom:
            type: geometry
            nullable: true
            requireSQLConversion: true
            column: the_geom
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: birds
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        station:
            targetEntity: Station
            cascade: {  }
            mappedBy: null
            inversedBy: birds
            joinColumns:
                station_id:
                    referencedColumnName: id
            orphanRemoval: false
        family:
            targetEntity: Family
            cascade: {  }
            mappedBy: null
            inversedBy: birds
            joinColumns:
                family_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        observations:
            targetEntity: BirdObservation
            cascade: {  }
            mappedBy: bird
        
    lifecycleCallbacks: {  }
