Yorku\JuturnaBundle\Entity\BirdGeometry:
    type: entity
    table: birds_geometry
    gedmo:
    translation:
        locale: localeField
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            nullable: false
            column: name
            gedmo:
                - translatable
        code:
            type: string
            length: 25
            nullable: true
            column: code
        geometryType:
            type: string
            length: 255
            nullable: true
            column: geometry_type
        lng:
            type: decimal
            unsigned: false
            nullable: false
        lat:
            type: decimal
            unsigned: false
            nullable: false
        radius:
            type: decimal
            unsigned: false
            nullable: true
            column: radius
        theGeom:
            type: geometry
            nullable: true
            requireSQLConversion: true
            column: the_geom
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    manyToOne:
     
        station:
            targetEntity: Station
            cascade: {  }
            mappedBy: null
            inversedBy: birds
            joinColumns:
                station_id:
                    referencedColumnName: id
            orphanRemoval: false
        family:
            targetEntity: Family
            cascade: {  }
            mappedBy: null
            inversedBy: birds
            joinColumns:
                family_id:
                    referencedColumnName: id
            orphanRemoval: false
        
    lifecycleCallbacks: {  }
