Yorku\JuturnaBundle\Entity\CategoryContents:
    type: entity
    table: category_contents
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        title:
            type: string
            length: 230
            fixed: false
            nullable: false
            column: title
        detail:
            type: text
            nullable: true
            column: detail
        layerId: 
            type: integer
            unsigned: false
            nullable: false  
            column: layer_id
        categoryId: 
            type: integer
            unsigned: false
            nullable: false  
            column: category_id            
        position: 
            type: integer
            unsigned: false
            nullable: true  
            column: position
        citation:
            type: string
            length: 230
            fixed: false
            nullable: true
            column: citation            
        citationLink:
            type: string
            length: 230
            fixed: false
            nullable: true
            column: citation_link
        description:
            type: text
            nullable: true
            column: description
        tags:
            type: array
            nullable: true
            column: tags
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update    
    oneToMany:
        contentdetails:
            targetEntity: Yorku\JuturnaBundle\Entity\CategoryContentDetails
            mappedBy: categorycontent             
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
              category_id:
                referencedColumnName: id
        layer:
            targetEntity: Map2u\CoreBundle\Entity\UploadfileLayer 
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
              layer_id:
                referencedColumnName: id
    manyToMany:                 
       displayLayers:
         targetEntity: Map2u\CoreBundle\Entity\UploadfileLayer
         inversedBy: {}
         orderBy:
             layerName: ASC
         joinTable:
           name: categorycontent_dlayers
           joinColumns:
             categorycontent_id:
               referencedColumnName: id
           inverseJoinColumns:
             layer_id:
               referencedColumnName: id                       
    lifecycleCallbacks: {  }
