Yorku\JuturnaBundle\Entity\Distribution:
    type: entity
    table: bird_distribution
    gedmo:
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        distributionName:
            type: string
            length: 255
            nullable: false
            column: distribution_name
        code:
            type: string
            length: 10
            column: code
    lifecycleCallbacks: {  }
