Yorku\JuturnaBundle\Entity\Family:
    type: entity
    table: bird_family
    gedmo:
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        familyName:
            type: string
            length: 255
            nullable: false
            column: family_name
        description:
            type: text
            nullable: true
            column: description
    oneToMany:
        birds:
            targetEntity: Bird
            cascade: {  }
            mappedBy: family
            
    lifecycleCallbacks: {  }
