Yorku\JuturnaBundle\Entity\HomepageDescription:
    type: entity
    table: homepage_description
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: title
        url:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: url
        published:
            type: boolean
            nullable: true
            column: published
        active:
            type: boolean
            nullable: true
            column: active
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        description:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
