Yorku\JuturnaBundle\Entity\IUCN:
    type: entity
    table: bird_iucn
    gedmo:
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        IUCNName:
            type: string
            length: 255
            nullable: false
            column: iucn_name
        code:
            type: string
            length: 10
            column: code
    lifecycleCallbacks: {  }
