Yorku\JuturnaBundle\Entity\Leadername:
    type: entity
    table: leadername
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        leadername:
            type: string
            length: null
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
