Yorku\JuturnaBundle\Entity\MapLayer:
    type: entity
    table: maplayer
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        layerTitle:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: layer_title
        layerName:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: layer_name
        WMSUrl:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: wms_url
        geoserverWorkspace:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: geoserver_workspace
        geoserverLayerName:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: geoserver_layer_name
        layerType:
            type: string
            length: 40
            fixed: false
            nullable: true
            column: layer_type
        layerEnabled:
            type: boolean
            nullable: true
            column: layer_enabled
        layerShowInSwitcher:
            type: boolean
            nullable: true
            column: layer_showinswitcher
        layerEPSG:
            type: string
            length: 40
            fixed: false
            nullable: true
            column: layer_epsg
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        description:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
