Yorku\JuturnaBundle\Entity\MapMeasurement:
    type: entity
    table: map_measurements

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            nullable: false
            column: measurement_name
        type:
            type: string
            length: 255
            nullable: true
            column: type
        radius:
            type: float
            nullable: true
            column: radius
        theGeom:
            type: geometry
            nullable: true
            requireSQLConversion: true
            column: the_geom
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
 
    lifecycleCallbacks: {  }
