Yorku\JuturnaBundle\Entity\ObservationDescription:
    type: entity
    table: bird_observationdescription
    gedmo:
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            nullable: false
            column: name
        code:
            type: string
            length: 5
            nullable: false
            column: code
        description:
            type: text
            nullable: true
            column: description
            
    lifecycleCallbacks: {  }
