Yorku\JuturnaBundle\Entity\Period:
    type: entity
    table: bird_period
    gedmo:
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        periodName:
            type: string
            length: 255
            nullable: false
            column: period_name
        code:
            type: string
            length: 10
            column: code
    lifecycleCallbacks: {  }
