Yorku\JuturnaBundle\Entity\PeriodStatus:
    type: entity
    table: bird_periodstatus
    gedmo:
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        statusName:
            type: string
            length: 255
            nullable: false
            column: status_name
        code:
            type: string
            length: 10
            column: code
    lifecycleCallbacks: {  }
