Yorku\JuturnaBundle\Entity\SchemaMigrations:
    type: entity
    table: schema_migrations
    fields:
        version:
            id: true
            type: string
            length: 255
            fixed: false
            nullable: false
            generator:
                strategy: SEQUENCE
    lifecycleCallbacks: {  }
