Yorku\JuturnaBundle\Entity\Season:
    type: entity
    table: bird_season
    gedmo:
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        seasonName:
            type: string
            length: 255
            nullable: false
            column: season_name
        code:
            type: string
            length: 10
            column: code
    lifecycleCallbacks: {  }
