Yorku\JuturnaBundle\Entity\TourismComments:
    type: entity
    table: user_tourism_comments
    gedmo:
    translation:
        locale: localeField
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            nullable: false
            column: title
            gedmo:
                - translatable
        code:
            type: string
            length: 25
            nullable: true
            column: code
        isPublished:
            type: boolean
            nullable: true
            column: is_published
        contentFormatter:
            type: text
            nullable: true
            column: content_formatter    
        rawContent:
            type: text
            nullable: true
            column: raw_content    
        content:
            type: text
            nullable: true
            column: content    
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            nullable: true
            inversedBy: user_tourisms
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        tourism:
            targetEntity: Tourism
            cascade: {  }
            mappedBy: null
            inversedBy: tourism_comments
            joinColumns:
                tourism_id:
                    referencedColumnName: id
            orphanRemoval: false
         
    lifecycleCallbacks: {  }
