Yorku\JuturnaBundle\Entity\TourismGeoms:
    type: entity
    table: user_tourism_geoms
    gedmo:
    translation:
        locale: localeField
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            nullable: false
            column: name
            gedmo:
                - translatable
        label:
            type: string
            length: 125
            nullable: true
            column: label
        icon:
            type: string
            length: 125
            nullable: true
            column: icon
        isEnabled:
            type: boolean
            nullable: true
            column: is_enabled
        isPublished:
            type: boolean
            nullable: true
            column: is_published
 
        theGeom:
            type: geometry
            nullable: true
            requireSQLConversion: true
            column: the_geom
        geometryType:
            type: string
            length: 255
            nullable: true
            column: geometry_type
        radius:
            type: decimal
            unsigned: false
            nullable: true
            column: radius
        style:
            type: text
            nullable: true
            column: style
    oneToMany:
       tourisms:
         targetEntity: Tourism
         mappedBy: tourismgeoms
      
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: tourismgeoms
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false                
    lifecycleCallbacks: {  }
