ibrows_newsletter:
  mandants:
    # generate a secure token for each mandant!
    default:    ThisTokenIsNotSoSecretChangeItdefault
    mandantA:   ThisTokenIsNotSoSecretChangeItMandantA
    mandantB:   ThisTokenIsNotSoSecretChangeItMandantB
  classes:
    # needed entities - see next step for creating them
    model:
      # most likely fos user
      user:         Application\Sonata\UserBundle\Entity\User
      # depends on the namespace you set at
      mandant:      Ibrows\Map2uBundle\Entity\Newsletter\Mandant
      newsletter:   Ibrows\Map2uBundle\Entity\Newsletter\Newsletter
      subscriber:   Ibrows\Map2uBundle\Entity\Newsletter\Subscriber
      design:       Ibrows\Map2uBundle\Entity\Newsletter\Design
      block:        Ibrows\Map2uBundle\Entity\Newsletter\Block
      group:        Ibrows\Map2uBundle\Entity\Newsletter\Group
      readlog:      Ibrows\Map2uBundle\Entity\Newsletter\Log\ReadLog
      sendlog:      Ibrows\Map2uBundle\Entity\Newsletter\Log\SendLog
      unsubscribelog: Ibrows\Map2uBundle\Entity\Newsletter\Log\Unsubscribelog
      sendsettings: Ibrows\Map2uBundle\Entity\Newsletter\SendSettings
      mailjob:      Ibrows\Map2uBundle\Entity\Newsletter\MailJob
            
  filesystem:
      block:
        # where to store uploaded files (e.g. image uploads)
        directory:  %kernel.root_dir%/../web/uploads/block
        # absolute path to the uploaded files
        public:     /uploads/block
        
parameters:
    database_driver_mandanta:   pdo_pgsql
    database_host_mandanta:     127.0.0.1
    database_port_mandanta:     ~
    database_name_mandanta:     map2u_newsletter_mandanta
    database_user_mandanta:     jzhao
    database_password_mandanta: jzhao

    database_driver_mandantb:   pdo_pgsql
    database_host_mandantb:     127.0.0.1
    database_port_mandantb:     ~
    database_name_mandantb:     map2u_newsletter_mandantb
    database_user_mandantb:     jzhao
    database_password_mandantb: jzhao