map2u_web:
    resource: "@Map2uWebBundle/Resources/config/routing.yml"
    prefix:   /

map2u_core:
    resource: "@Map2uCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
yorku_juturna:
    resource: "@YorkuJuturnaBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
  path: /{_locale}
  defaults: { _controller: Map2uCoreBundle:Welcome:index, _locale: en}
  requirements:
      _locale: en|es

      
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
    requirements:
      _locale: en|es

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    requirements:
      _locale: en|es


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
      _locale: en|es

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
      _locale: en|es

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    requirements:
      _locale: en|es
 
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
soanata_user:
     resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
     prefix: /admin
      