security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        admin:
#            pattern:      /admin(.*)
#            form_login:
#                provider:       fos_userbundle
#                login_path:     /admin/login
#                use_forward:    false
#                check_path:     /admin/login_check
#                failure_path:   null
#            logout:
#                path:           /admin/logout
#            anonymous:    true
#        # -> end custom configuration
# 
        main:
            pattern:  .*
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                use_forward:    false
                login_path: fos_user_security_login
                csrf_provider: form.csrf_provider
                success_handler: map2u_webgis_core.authentication.success_handler
                failure_handler: map2u_webgis_core.authentication.failure_handler
 # no this item               csrf_protection:  false
            logout: 
                path: fos_user_security_logout
#                target: index          
            anonymous:    true

    acl:
        connection: default
 
    access_control:
        - { path: ^/(en|es)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY } # for the case of a failed login
        - { path: ^/(en|es)/user/new$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/user/check-confirmation-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/user/confirm/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/user/confirmed$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/user/request-reset-password$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/user/send-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/user/check-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|es)/user/reset-password/, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/admin/, role: ROLE_ADMIN }
