parameters:
 #   wowo_newsletter.contact_manager.class: Your\Bundle\NewsletterContactManager
 #   wowo_newsletter.model.contact.class: Your\Bundle\Entity\User
    wowo_newsletter: ~
#        queue (default: newsletter_tube) - Beanstalkd tube name
#        default.sender_name (default: Wojciech Sznapka) - "from" name in email messages
#        default.sender_email (default: wojciech@sznapka.pl) - "from" address in email messages
#        form.can.choose.contacts.via.form (default: true) - determines if contacts can be choosen using form
#        form.has.delayed.sending (default: true) - determines wheter form allows to delay mailing (setting send date)

stfalcon_tinymce:
    include_jquery: true
    theme:
        advanced:
            mode: "textareas"
            theme: "advanced"
            theme_advanced_buttons1: "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,separator,bullist,numlist,link,unlink"
            theme_advanced_buttons2: ""
            theme_advanced_buttons3: ""
            theme_advanced_toolbar_location: "top"
            
wowo_newsletter:
    placeholders:
        firstname:  getFirstname
        lastname:   getLastname
        email:      getEmail
    #templates:
    #    'main template': %kernel.root_dir%/Resources/templates/newsletter/mailing.html