sonata_user:
    security_acl: true
    manager_type: orm
#    impersonating_route:    homepage # or any route you want to use
    class:                  # Entity Classes
#        user:               Map2u\Manifold\HealthBundle\Entity\Users
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group    

#    security_acl:             false
##    table:
##        user_group:           fos_user_user_group
#    class:                  # Entity Classes
#        user:               Map2u\Manifold\HealthBundle\Entity\Users
##        user:               Application\Sonata\UserBundle\Entity\User
#        group:              Application\Sonata\UserBundle\Entity\Group    

    impersonating: 
    #sonata_user_impersonating 
#        route:                sonata_admin_dashboard
        #    impersonating:
        route:                page_slug
        parameters:           { path: / }

    google_authenticator:
        server:               %sonata_user.google_authenticator.server%
        enabled:              true

    manager_type:             orm

    profile:
        form:
            type:                 sonata_user_profile
            handler:              sonata.user.profile.form.handler.default
            name:                 sonata_user_profile_form
            validation_groups:
                # Defaults:
                - Profile
                - Default
#    admin:
#        user:
#            class:    Application\Sonata\UserBundle\Admin\Model\UserAdmin