parameters:
#    yorku_juturna.example.class: Yorku\JuturnaBundle\Example

services:


    yorku_juturna.admin.member_ship:
        class: Yorku\JuturnaBundle\Admin\MemberShipAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\MemberShip, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: MemberShip}

    yorku_juturna.admin.graph_chart:
        class: Yorku\JuturnaBundle\Admin\GraphChartAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\GraphChart, YorkuJuturnaBundle:GraphChartAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: GraphChart}

    yorku_juturna.admin.category_contents:
        class: Yorku\JuturnaBundle\Admin\CategoryContentsAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\CategoryContents, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CategoryContents}

    yorku_juturna.admin.category:
        class: Yorku\JuturnaBundle\Admin\CategoryAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\Category, YorkuJuturnaBundle:CategoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    yorku_juturna.admin.category_content_details:
        class: Yorku\JuturnaBundle\Admin\CategoryContentDetailsAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\CategoryContentDetails, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CategoryContentDetails}
    yorku_juturna.admin.homepage_flash:
        class: Yorku\JuturnaBundle\Admin\HomepageFlashAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\HomepageFlash, YorkuJuturnaBundle:HomepageFlashAdmin,@service_container]
        tags:
            - {name: sonata.admin, manager_type: orm, group: homepage, label: HomepageFlash}
    
    yorku_juturna.admin.homepage_image:
        class: Yorku\JuturnaBundle\Admin\HomepageImageAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\HomepageImage, YorkuJuturnaBundle:HomepageImageAdmin,@service_container]
        tags:
            - {name: sonata.admin, manager_type: orm, group: homepage, label: HomepageImage}
    
    yorku_juturna.admin.homepage_description:
        class: Yorku\JuturnaBundle\Admin\HomepageDescriptionAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\HomepageDescription, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: homepage, label: HomepageDescription}

    yorku_juturna.admin.story:
        class: Yorku\JuturnaBundle\Admin\StoryAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\Story, YorkuJuturnaBundle:StoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Story}

    yorku_juturna.admin.indicator:
        class: Yorku\JuturnaBundle\Admin\IndicatorAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\Indicator,  SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Indicator}

    yorku_juturna.admin.indicator_benefit:
        class: Yorku\JuturnaBundle\Admin\IndicatorBenefitAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\IndicatorBenefit, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: IndicatorBenefit}

    yorku_juturna.admin.indicator_benefit_image:
        class: Yorku\JuturnaBundle\Admin\IndicatorBenefitImageAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\IndicatorBenefitImage, YorkuJuturnaBundle:IndicatorBenefitImageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: IndicatorBenefitImage}

    yorku_juturna.admin.indicator_reference:
        class: Yorku\JuturnaBundle\Admin\IndicatorReferenceAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\IndicatorReference, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: IndicatorReference}

    yorku_juturna.admin.eco_system_service:
        class: Yorku\JuturnaBundle\Admin\EcoSystemServiceAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\EcoSystemService, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: EcoSystemService}

    yorku_juturna.admin.human_well_being_domain:
        class: Yorku\JuturnaBundle\Admin\HumanWellBeingDomainAdmin
        arguments: [~, Yorku\JuturnaBundle\Entity\HumanWellBeingDomain, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: HumanWellBeingDomain}
    yorku_juturna.block.indicator_column:
                class: Yorku\JuturnaBundle\Block\IndicatorColumnBlockService
                arguments:
                    - "yorku_juturna.block.indicator_column"
                    - "@templating"
                    - "@doctrine.orm.entity_manager"
                tags:
                    -  { name: sonata.block, alias: yorku_juturna.block.indicator_column}
