parameters:
#    map2u_core.example.class: Map2u\CoreBundle\Example

services:
#    map2u_core.example:
#        class: %map2u_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    map2u_webgis_core.authentication.success_handler:
        class: Map2u\CoreBundle\Listener\AuthenticationSuccessHandler
        parent: security.authentication.success_handler

    map2u_webgis_core.authentication.failure_handler:
        class: Map2u\CoreBundle\Listener\AuthenticationFailureHandler
        parent: security.authentication.failure_handler  
        
 #// src/Acme/DemoBundle/Resources/config/services.yml
  #  map2u_webgis_core.registration_listener:
  #      class: Map2u\CoreBundle\EventListener\RegistrationListener
  #      arguments: []
  #      tags:
  #          - { name: kernel.event_subscriber } 
            
    map2u.twig_core.map2u_extension:
        class: Map2u\CoreBundle\Twig\Map2uExtension
        tags:
            - { name: twig.extension }